version: "0.1"
services:
  cargo_stylus_v0.4:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_TAG: v0.4.2.4
    image: cargo_stylus_v0.4
    container_name: cargo_stylus_v0.4
    ports:
      - "8004:8080"
  cargo_stylus_v0.5:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_TAG: v0.5.0
    image: cargo_stylus_v0.5
    container_name: cargo_stylus_v0.5
    ports:
      - "8005:8080"
