version: "3.8"
services:
  # arm_cargo_stylus_v0.4.2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.arm
  #     args:
  #       GIT_TAG: v0.4.2.4
  #   image: arm_cargo_stylus_v0.4.2
  #   container_name: arm_cargo_stylus_v0.4.2
  #   platform: linux/arm64
  #   ports:
  #     - "8042:8080"
  #   volumes:
  #     - ./project:/workspace
  #   stdin_open: true
  #   tty: true

  arm_cargo_stylus_v0.5.1:
    build:
      context: .
      dockerfile: Dockerfile.arm
      args:
        GIT_TAG: v0.5.1
    image: arm_cargo_stylus_v0.5.1
    container_name: arm_cargo_stylus_v0.5.1
    platform: linux/arm64
    ports:
      - "8051:8080"
    volumes:
      - ./project:/workspace
    environment:
      - CARGO_TARGET_DIR=/cargo-target
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "2G"
        reservations:
          cpus: "1.0"
          memory: "1G"
  # depends_on:
  #   - arm_cargo_stylus_v0.4.2

  arm_cargo_stylus_v0.5.3:
    build:
      context: .
      dockerfile: Dockerfile.arm
      args:
        GIT_TAG: v0.5.3
    image: arm_cargo_stylus_v0.5.3
    container_name: arm_cargo_stylus_v0.5.3
    platform: linux/arm64
    ports:
      - "8053:8080"
    volumes:
      - ./project:/workspace
    environment:
      - CARGO_TARGET_DIR=/cargo-target
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "2G"
        reservations:
          cpus: "1.0"
          memory: "1G"
    # depends_on:
    #   - arm_cargo_stylus_v0.5.1

  # amd_cargo_stylus_v0.4.2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.amd
  #     args:
  #       GIT_TAG: v0.4.2.4
  #   image: amd_cargo_stylus_v0.4.2
  #   container_name: amd_cargo_stylus_v0.4.2
  #   platform: linux/arm64
  #   ports:
  #     - "8142:8080"
  #   volumes:
  #     - ./project:/workspace
  #   stdin_open: true
  #   tty: true

  # amd_cargo_stylus_v0.5.1:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.amd
  #     args:
  #       GIT_TAG: v0.5.1
  #   image: amd_cargo_stylus_v0.5.1
  #   container_name: amd_cargo_stylus_v0.5.1
  #   platform: linux/arm64
  #   ports:
  #     - "8151:8080"
  #   volumes:
  #     - ./project:/workspace
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - amd_cargo_stylus_v0.4.2

  # amd_cargo_stylus_v0.5.3:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.amd
  #     args:
  #       GIT_TAG: v0.5.3
  #   image: amd_cargo_stylus_v0.5.3
  #   container_name: amd_cargo_stylus_v0.5.3
  #   platform: linux/arm64
  #   ports:
  #     - "8153:8080"
  #   volumes:
  #     - ./project:/workspace
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - amd_cargo_stylus_v0.5.1
